name: CI

on: push

jobs:

  lint:

    name: Lint
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependendencies
      uses: ./.github/actions/setup

    - name: Lint
      run: make lint

    - name: Typecheck
      run: make typecheck

  test:

    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependendencies
      uses: ./.github/actions/setup

    - name: Install system dependencies
      run: sudo apt-get -y install socat

    - name: Test
      run: python -m unittest -v --locals --buffer
      working-directory: diode

  publish:

    name: Publish
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags')

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependendencies
      uses: ./.github/actions/setup

    - name: Install pypa/build
      run: pip install build
      env:
        PIP_PROGRESS_BAR: off
        PIP_DISABLE_PIP_VERSION_CHECK: 1

    - name: Build distribution
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: diode
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8
      with:
        print-hash: true
